name: "WriftAI CLI Action"
description: "Setup WriftAI CLI, wriftai, on GitHub Actions runners"
author: "WriftAI"

branding:
  icon: 'play'
  color: 'green'

inputs:
  version:
    description: "Release version to install , or 'latest'"
    required: false
    default: "latest"

outputs: 
  version:
    description: The version of WriftAI CLI that was installed 
    value: ${{steps.set-version.outputs.version}}

runs:
  using: "composite"
  steps:
    - name: Install CLI
      uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2
      id: install 
      with:
        repo: "wriftai/cli"
        # TODO: Remove setting PAT once CLI is publicly accessible.
        token: ${{ env.WRIFTAI_SETUP_CLI_PAT }}
        tag: ${{ inputs.version }}

    - name: Unblock Windows executable (Windows only)
      shell: pwsh
      run: |
        Write-Host "=== Unblocking Windows executable ==="
        $exe_path = "C:\hostedtoolcache\windows\wriftai\cli\${{ inputs.version }}\windows-x64\wriftai.exe"
        if (Test-Path $exe_path) {
          Write-Host "Unblocking: $exe_path"
          Unblock-File -Path $exe_path
          Write-Host "Unblocked successfully"
        } else {
          Write-Host "Executable not found at: $exe_path"
        }
      if: runner.os == 'Windows'

    - name: Set installed version
      id: set-version
      shell: pwsh
      run: |
        
        $cli_output = wriftai version --skip-update-check
        Write-Host "CLI output: '$cli_output'"
        
        if (-not $cli_output) {
          Write-Host "Trying with .exe extension..."
          $cli_output = wriftai.exe version --skip-update-check
          Write-Host "CLI output with .exe: '$cli_output'"
        }
        
        $version = $cli_output | Select-String -Pattern '(\d+\.\d+\.\d+)' | ForEach-Object { $_.Matches.Groups[1].Value }
        
        echo "version=$version" >> $env:GITHUB_OUTPUT

