name: "WriftAI CLI Action"
description: "Setup WriftAI CLI, wriftai, on GitHub Actions runners"
author: "WriftAI"

branding:
  icon: 'play'
  color: 'green'

inputs:
  version:
    description: "Release version to install , or 'latest'"
    required: false
    default: "latest"

outputs: 
  version:
    description: The version of WriftAI CLI that was installed 
    value: ${{steps.set-version.outputs.version}}

runs:
  using: "composite"
  steps:
    - name: Install CLI
      uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2
      id: install 
      with:
        repo: "wriftai/cli"
        # TODO: Remove setting PAT once CLI is publicly accessible.
        token: ${{ env.WRIFTAI_SETUP_CLI_PAT }}
        tag: ${{ inputs.version }}

    - name: Set installed version
      id: set-version
      shell: pwsh
      run: |
        # Debug: Check if wriftai command exists and works
        Write-Host "=== Checking wriftai command ==="
        Get-Command wriftai -ErrorAction Continue
        $cli_output = wriftai version --skip-update-check
        Write-Host "CLI output: $cli_output"
        
        # Try multiple extraction methods
        $version = $cli_output | Select-String -Pattern '(\d+\.\d+\.\d+)' | ForEach-Object { $_.Matches.Groups[1].Value }
        Write-Host "Extracted version (Method 1): $version"
        
        # Alternative method if first fails
        if (-not $version) {
          $version = $cli_output -replace '.*?(\d+\.\d+\.\d+).*', '$1'
          Write-Host "Extracted version (Method 2): $version"
        }
        
        # Final fallback
        if (-not $version) {
          $version = "unknown"
          Write-Host "Using fallback version: $version"
        }
        
        Write-Host "=== Setting output version: $version ==="
        echo "version=$version" >> $env:GITHUB_OUTPUT
