name: "WriftAI CLI Action"
description: "Setup WriftAI CLI, wriftai, on GitHub Actions runners"
author: "WriftAI"

branding:
  icon: 'play'
  color: 'green'

inputs:
  version:
    description: "Release version to install , or 'latest'"
    required: false
    default: "latest"

outputs: 
  version:
    description: The version of WriftAI CLI that was installed 
    value: ${{steps.version-output.outputs.version}}

runs:
  using: "composite"
  steps:
    - name: Install CLI
      uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2
      id: install 
      with:
        repo: "wriftai/cli"
        # TODO: Remove setting PAT once CLI is publicly accessible.
        token: ${{ env.WRIFTAI_SETUP_CLI_PAT }}
        tag: ${{ inputs.version }}

    - name: Get installed version (Linux/macOS)
      id: set-version-unix
      shell: bash
      run: |
        version=$(wriftai version --skip-update-check | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
        echo "VERSION=$version" >> $GITHUB_ENV
      if: runner.os != 'Windows'

    - name: Get installed version (Windows)
      id: set-version-windows
      shell: pwsh
      run: |
        $version = wriftai version --skip-update-check | Select-String -Pattern '(\d+\.\d+\.\d+)' | ForEach-Object { $_.Matches.Groups[1].Value }
        echo "VERSION=$version" >> $env:GITHUB_ENV
      if: runner.os == 'Windows'

    - name: Set final version output
      id: version-output
      shell: bash
      run: |
        echo "version=$VERSION" >> $GITHUB_OUTPUT
